site_name: Immview 3
pages:
    - Start: index.md
    - Docs:
        - Observable: Observable.md
        - Atom: Atom.md
        - Combine: Combine.md
        - Domain: Domain.md
    - Guides:
        - Atom or Observable?: AtomObservableDiff.md
theme: 'cinder'
repo_url: https://github.com/arturkulig/immview
docs_dir: docs_md
site_dir: docs
